# fly.toml app configuration file generated for smallweb-proxy on 2024-05-30T20:13:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smallweb-proxy'
primary_region = 'cdg'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1
processes = ['app']


[[services]]
http_checks = []
internal_port = 2222
processes = ["app"]
protocol = "tcp"
script_checks = []

[[services.ports]]
handlers = []
port = 22
